name: Test Docker Image
on:
  push:
    branches:
      - main

jobs:
  test-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}/errorllmaction

      - name: Run Docker image
        run: docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}/errorllmaction

  send-error:
    runs-on: ubuntu-latest
    needs: test-docker-image
    steps:
      - name: Print this workflow run ID
        run: "echo 'Workflow run ID: ${{ github.run_id }}'"
        
      - name: Get the API response for this workflow run
        run: |
            gh api 
            -H "Accept: application/vnd.github+json" 
            -H "X-GitHub-Api-Version: 2022-11-28"
            /repos/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
